[config]
keep_std = true

[game_list]
"com.tencent.tmgp.sgame" = [60, 90, 120]

[powersave]
margin_fps = 5.0
core_temp_thresh = 80000

[balance]
margin_fps = 3.5
core_temp_thresh = 90000

[performance]
margin_fps = 1.5
core_temp_thresh = 95000

[fast]
margin_fps = 0
core_temp_thresh = 95000