# Copyright 2023-2025, dependabot[bot], shadow3, shadow3aaa
#
# This file is part of fas-rs.
#
# fas-rs is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# fas-rs is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along
# with fas-rs. If not, see <https://www.gnu.org/licenses/>.

name: release
permissions:
  contents: write
on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup ndk
        run: |
          ndk_url=$(wget -qO- https://github.com/android/ndk/releases/latest | grep -e 'https://dl.google.com/android/repository/android-ndk-.*-linux.zip' | sed -n 's/.*<a href="\([^"]*\)".*/\1/p')
          wget -O ndk.zip $ndk_url -nv
          mkdir ~/ndk_temp
          unzip ndk.zip -d ~/ndk_temp 2>&1 > /dev/null
          mv ~/ndk_temp/*/* ~/ndk_temp

      - name: Setup rust toolchains
        run: |
          rustup default nightly
          rustup target add aarch64-linux-android
          rustup component add rust-src
          rustup update

      - name: Install cargo ndk
        run: cargo install cargo-ndk

      - name: Other deps
        run: |
          sudo apt update
          sudo apt install gcc-multilib

      - name: Build
        run: |
          export ANDROID_NDK_HOME=$(realpath ~/ndk_temp)
          export ANDROID_NDK_ROOT=$ANDROID_NDK_HOME

          cargo xtask build -r -v

      - name: Prepare artifacts
        run: |
          mkdir -p output/artifact/release
          unzip "output/fas-rs(release).zip" -d output/artifact/release
          cd output/artifact/release
          zip -r9 fas-rs-mod.zip *

      - name: Upload release
        uses: ncipollo/release-action@v1.14.0
        with:
          allowUpdates: true
          removeArtifacts: true
          name: fas-rs(release)
          tag: "Run-${{ github.run_number }}"
          artifacts: output/artifact/release/fas-rs-mod.zip
          body: |
            Commit: ${{ github.sha }}
            ### Note: 
            - 定期同步fas-rs上游
            - 只兼容arm64-v8a安卓设备（64位）
            - 配置项与fas-rs-mod同步
            - 模块内不再放置debug版的fas-rs二进制

            ### Credit
            - fas-rs来自`shadow3aaa`
            - scene-patcher来自`Dog_EZ`

            ### 本仓库的意义
            解决`Dog_EZ`更新过慢的问题
